name: Cache any changes to shell environment
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        with:
          name: chiroptical
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-store --query --references $(nix-instantiate shell.nix) | xargs nix-store --realise | xargs nix-store --query --requisites | cachix push chiroptical
