name: Build LaTeX Document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        name: chiroptical
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build
